build:
  image: bjodah/bjodahimg16:v1.2
  commands:
    - ./scripts/ci.sh chempy
    - (cd examples/; python -m pip install --force bokeh==0.11.1; for f in bokeh_*.py; do python -m bokeh html $f; done)
    - ./scripts/prepare_deploy.sh

deploy:

  rsync:
    host: hera.physchem.kth.se
    user: chempy
    port: 22
    source: deploy/
    target: ~
    recursive: true
    delete: false
