build:
  image: bjodah/bjodahimg16dev:v1.3
  environment:
    - CPLUS_INCLUDE_PATH=/opt/boost_1_65_0/include
    - LIBRARY_PATH=/opt/boost_1_65_0/lib
    - LD_LIBRARY_PATH=/opt/boost_1_65_0/lib
  commands:
    - bash -c '[[ $(python setup.py --version) =~ ^[0-9]+.* ]]'
    - PYCVODES_LAPACK=lapack,blas ./scripts/ci.sh chempy
    - (cd examples/; python -m pip install --force bokeh==0.11.1; for f in bokeh_*.py; do python -m bokeh html $f; done)
    - ./scripts/prepare_deploy.sh
    - PATH=/opt/miniconda3/bin:$PATH conda config --add channels bjodah  # sym, pyodesys, pyneqsys
    - PATH=/opt/miniconda3/bin:$PATH conda build conda-recipe
    - if grep "DO-NOT-MERGE!" -R . --exclude ".drone.yml"; then exit 1; fi

deploy:

  rsync:
    host: hera.physchem.kth.se
    user: chempy
    port: 22
    source: deploy/
    target: ~
    recursive: true
    delete: false
