image: bjodah/dockerfile-bjodah-scicomp:14.04c
git:
    path: github.com/bjodah/chempy
script:
  - if [[ "$DRONE_BRANCH" =~ ^v[0-9]+.[0-9]?* ]]; then export CHEMPY_RELEASE_VERSION=$DRONE_BRANCH; echo ${CHEMPY_RELEASE_VERSION} | tail -c +2 > __conda_version__.txt; fi
  - pip install --user -r requirements.txt
  - pip3 install --user -r requirements.txt
  - PYTHONPATH=$(pwd) ./scripts/run_tests.sh --cov chempy --cov-report html
  - python2 setup.py sdist
  - ./scripts/generate_docs.sh
  - ssh chempy@hera.physchem.kth.se "mkdir -p ~/public_html/$DRONE_BRANCH"
  - scp -r doc/_build/html/ dist/* htmlcov/ chempy@hera.physchem.kth.se:~/public_html/$DRONE_BRANCH
  - touch doc/_build/html/.nojekyll
  - git config --global user.name "drone"
  - git config --global user.email "drone@hera.physchem.kth.se"
  - if [[ "$DRONE_BRANCH" == "master" ]]; then ./scripts/github_upload.sh doc/_build/html bjodah chempy gh-pages; fi
  - if [[ "$DRONE_BRANCH" == "master" ]]; then scp -r asv.conf.json benchmarks/ chempy@hera.physchem.kth.se:~; fi
  - if [[ "$DRONE_BRANCH" == "master" ]]; then ssh chempy@hera.physchem.kth.se 'source /etc/profile; asv run -k -e >asv-run.log; asv publish>asv-publish.log'; fi
