version: 2

jobs:
  build:
    docker:
      - image: continuumio/miniconda
    steps:
      - checkout
      - run:
          name: Configure conda
          commands:
            - conda config --add channels conda-forge
            - conda config --set show_channel_urls true
            - conda config --set always_yes yes
            - conda install conda-build
            - conda build conda-recipe/
