{% set name = "chempy" %}
{% set version = "0.5.0.git" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: ../

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - numpy
    - sympy
    - scipy
    - matplotlib
    - quantities
    - sym
    - appdirs
    - pyodesys
    - pyneqsys
    - pyparsing
  run:
    - python
    - numpy
    - sympy
    - scipy
    - matplotlib
    - quantities
    - sym
    - appdirs
    - pyodesys
    - pyneqsys
    - pyparsing

test:
  imports:
    - {{ name }}

about:
  home: https://github.com/bjodah/chempy
  license: BSD 2-Clause
  license_file: LICENSE
  summary: 'Python package useful for (physical) chemistry'
  doc_url: https://bjodah.github.io/{{ name }}/latest

extra:
  recipe-maintainers:
    - bjodah
